development:
  adapter: postgresql
  encoding: unicode
  database: kickstarter
  pool: 5
  username: my_user
  password: 12345

test:
  adapter: postgresql
  encoding: unicode
  database: kickstarter_test
  pool: 5
  username: my_user
  password: 12345

production:
  adapter: postgresql
  encoding: unicode
  database: kickstarter_production
  pool: 5
  username: my_user
  password: 12345
